# Generated by Django 5.2.8 on 2025-11-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
